channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal =5.2.4
  - python =3.6
  - gatk4 =4.1.2.0
  - hisat2 =2.1.0
  - samtools =1.9
  - sra-tools
  - stringtie
  - biopython
  - git
  - maven
  - fastp
  - star =2.7.0f-0
  - numpy =1.16.4
  - biopython
  - bcbio-gff
  - pandas
  - rsem =1.3.2-0
  - star-fusion =1.6.0
  - perl-carp-assert # for STAR-Fusion
  - igv-reports # for STAR-Fusion
  - trinity=2.8.4-0 # for STAR-Fusion
  - r # for ProteomeGenerator
  - bioconductor-biostrings # for ProteomeGenerator
  - picard # for ProteomeGenerator
  - transdecoder # for ProteomeGenerator
  - gffread # for ProteomeGenerator
  - blast # for ProteomeGenerdator
