sra: [SRR629563] #  can leave empty sras as 1) empty list 2) undefined/null
analysisDirectory: [AnalysisFolder] # for paths to drive e.g. /mnt/c/AnalysisFolder
species: "Homo_sapiens"
genome: "GRCh38"
release: "100"
organism: "human" # based on uniprot
fq: []
analyses: [isoform,variant]
spritzversion: "0.2.0"
