sra: [SRR629563] #  paired-end SRAs, comma separated, can leave empty
fq: [TestPairedEnd] # paired-end fastq prefixes, comma separated, can leave empty
sra_se: [SRR8070095] # single-end SRAs, comma separated, can leave empty
fq_se: [TestSingleEnd] # single-end fastq prefixes, comma separated, can leave empty
analysisDirectory: [AnalysisFolder] # for paths to drive e.g. /mnt/c/AnalysisFolder
species: "Homo_sapiens"
genome: "GRCh38"
release: "100"
organism: "human" # based on uniprot
analyses: [isoform,variant]
spritzversion: "0.2.3" # should be the same here, common.smk, and MainWindow.xml.cs
